<?php

/**
 * An example test class to show syntax and documentation.
 *
 * This test class is only an example to serve as a reference or be deleted.<br />
 * Last modified in 2022-04-21<br />
 * PHP version 7.4.23<br />
 *
 * @copyright   2022 Leonardo Pinheiro
 * @author      __Leonardo Pinheiro__ <info@leonardopinheiro.net>
 * @link        https://www.leonardopinheiro.net Leonardo Pinheiro Designer's website
 *
 * @see         https://stackoverflow.com/questions/45506414/how-to-document-phpunit-tests How to document PHPUnit tests
 */

namespace Test\PHP_Boilerplate\classes;

require_once(__DIR__ . '/../../../src/shared/autoload.php');


use PHP_Boilerplate\classes\ExampleSuperclass;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-04-22 at 00:40:21.
 */
class ExampleSuperclassTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var ExampleSuperclass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new ExampleSuperclass();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers PHP_Boilerplate\classes\ExampleSuperclass::returnMessage
     */
    public function testReturnMessage()
    {
        $expected_result = "The constructor of the superclass received the number: 10.<br />";
        $result = $this->object->returnMessage();
        $this->assertEquals($expected_result, $result);
    }
}
